name: 'Setup Go'
description: 'Configures Go and sets up Git for private module access.'
inputs:
  gh-token:
    description: 'PAT used for pulling Go modules.'
    default: ''
    required: false

runs:
  using: "composite"
  steps:

  - uses: actions/setup-go@v4
    with:
      go-version-file: 'go.mod'

  - id: go-env
    shell: bash
    env:
      ACCESS_TOKEN: '${{ inputs.gh-token }}'
    run: |
      if [ -n "${ACCESS_TOKEN}" ]; then
      	cat <<-EOF > ~/.netrc
      	machine github.com
      	login x-access-token
      	password ${ACCESS_TOKEN}
      	EOF
      fi
      go env -w "GOPRIVATE=github.com/${{ github.repository_owner }}/*"

  - id: goreleaser-env
    shell: bash
    run: |
      flags=()
      if [ -f "./.github/RELEASE_TEMPLATE.md" ]; then
      	flags+=(--release-notes ./.github/RELEASE_TEMPLATE.md)
      fi
      if [ "${GITHUB_REF_TYPE}" != "tag" ]; then
      	flags+=(--snapshot)
      fi
      if (( ${#flags[@]} )); then
      	echo "GORELEASER_FLAGS=${flags[@]}" >> $GITHUB_ENV
      fi
