name: 'Setup Go'
description: 'Configures Go and sets up Git/SSH for private module access.'
inputs:
  go-version:
    description: 'The Go version to download (if necessary) and use. Supports semver spec and ranges.'
    default: '^1.17'
    required: false
  ssh-private-key:
    description: 'Private SSH key to register in the SSH agent.'
    required: true

runs:
  using: "composite"
  steps:

  - uses: actions/setup-go@v2
    with:
      go-version: '${{ inputs.go-version}}'

  - uses: webfactory/ssh-agent@v0.5.4
    with:
      ssh-private-key: '${{ inputs.ssh-private-key }}'

  - shell: bash
    run: |
      go env -w "GOPRIVATE=github.com/${{ github.repository_owner }}"
      git config --global \
        "url.git@github.com:${{ github.repository_owner }}.insteadOf" \
        "https://github.com/${{ github.repository_owner }}"
