name: 'Setup Go'
description: 'Configures Go and sets up Git/SSH for private module access.'
inputs:
  go-version:
    description: 'The Go version to download (if necessary) and use. Supports semver spec and ranges.'
    default: '~1.17'
    required: false
  ssh-private-key:
    description: 'Private SSH key to register in the SSH agent.'
    default: ''
    required: false

runs:
  using: "composite"
  steps:

  - uses: actions/setup-go@v3
    with:
      go-version: '${{ inputs.go-version }}'

  - id: go-env
    shell: bash
    run: |
      #git config --global \
      #  "url.git@github.com:${{ github.repository_owner }}.insteadOf" \
      #  "https://github.com/${{ github.repository_owner }}"
      git config --global http.https://github.com/gramLabs/.extraheader \
          "AUTHORIZATION: basic $(echo -n "x-access-token:${{ inputs.ssh-private-key }}" | base64 -w 0)"
      go env -w "GOPRIVATE=github.com/${{ github.repository_owner }}"
      echo "::set-output name=go-cache::$(go env GOCACHE)"
      echo "::set-output name=go-mod-cache::$(go env GOMODCACHE)"

  - uses: actions/cache@v3
    with:
      path: |
        ${{ steps.go-env.outputs.go-cache }}
        ${{ steps.go-env.outputs.go-mod-cache }}
      key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      restore-keys: |
        ${{ runner.os }}-go-

#  - uses: webfactory/ssh-agent@v0.5.4
#    if: inputs.ssh-private-key != ''
#    with:
#      ssh-private-key: '${{ inputs.ssh-private-key }}'
