name: 'Setup Go'
description: 'Configures Go and sets up Git for private module access.'
inputs:
  gh-token:
    description: 'PAT used for pulling Go modules.'
    default: ''
    required: false

runs:
  using: "composite"
  steps:

  - uses: actions/setup-go@v6
    with:
      go-version-file: 'go.mod'
      cache-dependency-path: '**/go.sum'

  - id: go-env
    shell: bash
    env:
      ACCESS_TOKEN: '${{ inputs.gh-token }}'
    run: |
      if [ -n "${ACCESS_TOKEN}" ]; then
        git config --global http.https://github.com/${{ github.repository_owner }}/.extraheader \
            "AUTHORIZATION: basic $(echo -n "x-access-token:${ACCESS_TOKEN}" | base64 -w 0)"
      fi
      go env -w "GOPRIVATE=github.com/${{ github.repository_owner }}/*"

  - id: goreleaser-env
    shell: bash
    run: |
      flags=()
      if [ -f "./.github/RELEASE_TEMPLATE.md" ]; then
      	flags+=(--release-notes ./.github/RELEASE_TEMPLATE.md)
      fi
      if [ "${GITHUB_REF_TYPE}" != "tag" ]; then
      	flags+=(--snapshot)
      fi
      if (( ${#flags[@]} )); then
      	echo "GORELEASER_FLAGS=${flags[@]}" >> $GITHUB_ENV
      fi
