name: 'Setup Go'
description: 'Configures Go and sets up Git for private module access.'
inputs:
  go-version:
    description: 'The Go version to download (if necessary) and use. Supports semver spec and ranges.'
    default: '~1.17'
    required: false
    deprecationMessage: 'The Go version is now read directly from the ./go.mod file'
  gh-token:
    description: 'PAT used for pulling Go modules.'
    default: ''
    required: false

runs:
  using: "composite"
  steps:

  - uses: actions/setup-go@v3
    with:
      go-version-file: 'go.mod'
      cache: true

  - id: go-env
    shell: bash
    env:
      ACCESS_TOKEN: '${{ inputs.gh-token }}'
    run: |
      if [ -n "${ACCESS_TOKEN}" ]; then
        git config --global http.https://github.com/gramLabs/.extraheader \
            "AUTHORIZATION: basic $(echo -n "x-access-token:${ACCESS_TOKEN}" | base64 -w 0)"
      fi
      go env -w "GOPRIVATE=github.com/${{ github.repository_owner }}"
