name: 'Build Push'
description: 'Builds and pushes a Docker image to GHCR.'
inputs:
  # User name associated with the PAT.
  ghcr-username:
    description: 'Username associated with the PAT used to authenticate to GHCR.'
    required: true
  # PAT for authenticating to GHCR, we cannot use the GITHUB_TOKEN because it would not
  # trigger subsequent actions necessary for continuous deployment.
  ghcr-password:
    description: 'PAT token used to authenticate to GHCR.'
    required: true
  cluster:
    description: 'The development cluster to target.'
    default: 'dev-1'
    required: false

runs:
  using: "composite"
  steps:

  - uses: docker/setup-buildx-action@v1

  - uses: docker/login-action@v1
    with:
      registry: ghcr.io
      username: '${{ inputs.ghcr-username }}'
      password: '${{ inputs.ghcr-password }}'

  - uses: docker/metadata-action@v3
    id: meta
    with:
      images: ghcr.io/${{ github.repository }}
      flavor: latest=false
      tags: type=sha

  - uses: docker/build-push-action@v2
    with:
      context: .
      push: true
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}

  - shell: bash
    env:
      GH_TOKEN: '${{ inputs.ghcr-password }}'
      GH_REPO: gramLabs/stormforge-app
    run: |
      gh workflow run promote_image_to_dev.yaml \
        --ref main \
        -f image="${{ steps.meta.outputs.tags }}" \
        -f cluster="${{ inputs.cluster }}"
