name: 'Build Push'
description: 'Builds and pushes a Docker image to GHCR.'
inputs:
  gh-token:
    description: 'PAT used for triggering workflows.'
    required: true
  build-args:
    description: 'Build arguments for the image'
    required: false
    default: ''

runs:
  using: "composite"
  steps:

  - uses: docker/setup-buildx-action@v3

  - uses: docker/login-action@v3
    with:
      registry: ghcr.io
      username: '${{ github.actor }}'
      password: '${{ github.token }}'

  - uses: docker/metadata-action@v5
    id: meta
    with:
      images: ghcr.io/${{ github.repository }}
      flavor: latest=false
      tags: type=sha

  - uses: docker/build-push-action@v5
    with:
      context: .
      push: true
      provenance: false
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      cache-from: type=gha
      cache-to: type=gha
      build-args: ${{ inputs.build-args }}

  - shell: bash
    env:
      GH_REPO: gramLabs/stormforge-app
      GH_TOKEN: ${{ inputs.gh-token }}
    run: |
      gh workflow run promote_image_to_dev.yaml \
        -f image="${{ steps.meta.outputs.tags }}"
