name: 'Build Push'
description: 'Builds and pushes a Docker image to GHCR.'
inputs:
  gh-token:
    description: 'PAT used for triggering workflows.'
    required: true
  cluster:
    description: 'The development cluster to target.'
    default: 'dev-1'
    required: false

runs:
  using: "composite"
  steps:

  - uses: docker/setup-buildx-action@v2.2.1
    id: buildx
    with:
      version: "latest"
      install: true
      # pin buildkit so we do not build attestation + bom manifests for now
      # see https://stormkore.slack.com/archives/C01KUGAJNF6/p1673530297642719
      driver-opts: |
        image=moby/buildkit:v0.10.6

  - uses: docker/login-action@v2
    with:
      registry: ghcr.io
      username: '${{ github.actor }}'
      password: '${{ github.token }}'

  - uses: docker/metadata-action@v4
    id: meta
    with:
      images: ghcr.io/${{ github.repository }}
      flavor: latest=false
      tags: type=sha

  - uses: docker/build-push-action@v3
    with:
      context: .
      push: true
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      cache-from: type=gha
      cache-to: type=gha

  - shell: bash
    env:
      GH_REPO: gramLabs/stormforge-app
      GH_TOKEN: ${{ inputs.gh-token }}
    run: |
      gh workflow run promote_image_to_dev.yaml \
        -f image="${{ steps.meta.outputs.tags }}" \
        -f cluster="${{ inputs.cluster }}"
