name: 'Setup Python'
description: 'Configures Python.'
inputs:
  python-version:
    description: 'The Python version to download (if necessary) and use.'
    default: '3.10'
    required: false

runs:
  using: "composite"
  steps:

  - uses: actions/setup-python@v5
    with:
      python-version: '${{ inputs.python-version }}'
      cache: 'pip'

  - shell: bash
    run: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      python setup.py develop
