# NOTE: This is the old workflow, you should migrate to either main-go-library, main-go-service, or main-go-software.

name: Main

on:
  workflow_call:
    inputs:
      fetch-depth:
        description: 'The fetch depth for checking out code. Must be 0 for GoReleaser to recognize tags.'
        default: 1
        required: false
        type: number
      upload-artifacts:
        description: 'If true, preserve build artifacts on the job.'
        default: false
        required: false
        type: boolean
      cluster:
        description: 'The development cluster to target.'
        default: 'dev-1'
        required: false
        type: string
    secrets:
      gh-token:
        description: 'PAT used for triggering workflows and pulling Go modules.'
        required: true
      homebrew-token:
        description: 'PAT used for publishing to the Homebrew Tap (CLI only).'
        required: false
      registry-username:
        description: 'Username for the StormForge registry'
        required: false
      registry-password:
        description: 'Password for the StormForge registry'
        required: false
    outputs:
      artifacts:
        description: Build result artifacts.
        value: ${{ jobs.deploy.outputs.artifacts }}
      metadata:
        description: Build result metadata.
        value: ${{ jobs.deploy.outputs.metadata }}

jobs:

  # Builds and pushes images to GHCR.
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    outputs:
      artifacts: ${{ steps.goreleaser.outputs.artifacts }}
      metadata: ${{ steps.goreleaser.outputs.metadata }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Set up Go
      uses: gramLabs/.github/.github/actions/setup-go@main
      with:
        gh-token: '${{ secrets.gh-token }}'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true
        # Pin buildkit to prevent SBOM generation that breaks ECR
        driver-opts: |
          image=moby/buildkit:v0.10.6

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: '${{ github.actor }}'
        password: '${{ github.token }}'

    - name: Login to StormForge Registry
      uses: docker/login-action@v2
      # Hack for testing secret with 'if'
      env:
        REGISTRY_USERNAME: '${{ secrets.registry-username }}'
      if: "${{ env.REGISTRY_USERNAME != '' }}"
      with:
        registry: registry.stormforge.io
        username: '${{ secrets.registry-username }}'
        password: '${{ secrets.registry-password }}'

    - name: Run GoReleaser
      id: goreleaser
      uses: goreleaser/goreleaser-action@v3
      env:
        GITHUB_TOKEN: '${{ secrets.gh-token }}'
        HOMEBREW_TAP_GITHUB_TOKEN: '${{ secrets.homebrew-token }}'
      with:
        version: latest
        args: release ${{ env.GORELEASER_FLAGS }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      if: '${{ inputs.upload-artifacts}}'
      with:
        name: dist-archives
        path: |
          dist/*_checksums.txt
          dist/*.tar.gz
          dist/*.zip

    - name: Deploy image
      env:
        GH_REPO: gramLabs/stormforge-app
        GH_TOKEN: ${{ secrets.gh-token }}
      run: |
        gh workflow run promote_image_to_dev.yaml \
          -f image="ghcr.io/${{ github.repository }}:${{ fromJson(steps.goreleaser.outputs.metadata).version }}" \
          -f cluster="${{ inputs.cluster }}"

