name: Main

on:
  workflow_call:
    inputs:
      go-version:
        description: 'The Go version to download (if necessary) and use. Supports semver spec and ranges.'
        default: '^1.17'
        required: false
        type: string
    secrets:
      # The SSH key should be a deploy key that gives access to gramLabs private repositories
      ssh-private-key:
        description: 'Private SSH key to register in the SSH agent.'
        required: false
      # User name associated with the PAT.
      ghcr-username:
        description: 'Username associated with the PAT used to authenticate to GHCR.'
        required: true
      # PAT for authenticating to GHCR, we cannot use the GITHUB_TOKEN because it would not
      # trigger subsequent actions necessary for continuous deployment.
      ghcr-password:
        description: 'PAT token used to authenticate to GHCR.'
        required: true

jobs:

  # Builds and pushes images to GHCR.
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: gramLabs/.github/.github/actions/setup-go@main
      with:
        go-version: '${{ inputs.go-version}}'
        ssh-private-key: '${{ secrets.ssh-private-key }}'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: '${{ secrets.ghcr-username }}'
        password: '${{ secrets.ghcr-password }}'

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release
