name: Main

on:
  workflow_call:
    inputs:
      go-version:
        description: 'The Go version to download (if necessary) and use. Supports semver spec and ranges.'
        default: '~1.17'
        required: false
        type: string
      fetch-depth:
        description: 'The fetch depth for checking out code. Must be 0 for GoReleaser to recognize tags.'
        default: 1
        required: false
        type: number
      cluster:
        description: 'The development cluster to target.'
        default: 'dev-1'
        required: false
        type: string
    secrets:
      # The SSH key should be a deploy key that gives access to gramLabs private repositories
      ssh-private-key:
        description: 'Private SSH key to register in the SSH agent.'
        required: false
      # User name associated with the PAT.
      ghcr-username:
        description: 'Username associated with the PAT used to authenticate to GHCR.'
        required: true
      # PAT for authenticating to GHCR, we cannot use the GITHUB_TOKEN because it would not
      # trigger subsequent actions necessary for continuous deployment.
      ghcr-password:
        description: 'PAT token used to authenticate to GHCR.'
        required: true
      # User for authenticating to the private StormForge registry.
      registry-username:
        description: 'Username for the StormForge registry'
        required: false
      # Password for authenticating to the private StormForge registry.
      registry-password:
        description: 'Password for the StormForge registry'
        required: false

jobs:

  # Builds and pushes images to GHCR.
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Set up Go
      uses: gramLabs/.github/.github/actions/setup-go@ghcr-pat
      with:
        go-version: '${{ inputs.go-version}}'
        ssh-private-key: '${{ secrets.ghcr-password }}'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        # TODO We aren't using GHCR for events, we can probably use GITHUB_TOKEN
        username: '${{ secrets.ghcr-username }}'
        password: '${{ secrets.ghcr-password }}'

    - name: Login to StormForge Registry
      uses: docker/login-action@v1
      # Hack for testing secret with 'if'
      env:
        REGISTRY_PASSWORD: '${{ secrets.registry-username }}'
      if: "${{ env.REGISTRY_PASSWORD != '' }}"
      with:
        registry: registry.stormforge.io
        username: '${{ secrets.registry-username }}'
        password: '${{ secrets.registry-password }}'

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      env:
        GITHUB_TOKEN: '${{ github.token }}'
      with:
        version: latest
        args: release

    - name: Deploy image
      env:
        GH_TOKEN: '${{ secrets.ghcr-password }}'
        GH_REPO: gramLabs/stormforge-app
      run: |
        gh workflow run promote_image_to_dev.yaml \
          --ref main \
          -f image="ghcr.io/${{ github.repository }}:sha-$(git rev-parse --short HEAD)" \
          -f cluster="${{ inputs.cluster }}"

