name: Pull Request

on:
  workflow_call:
    secrets:
      gh-token:
        description: 'PAT used for pulling Go modules.'
        required: false

jobs:

  # Runs the linter with a minimal set of default rules.
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: gramLabs/.github/.github/actions/setup-go@main
      with:
        gh-token: '${{ secrets.gh-token }}'

    - name: Configure Linter
      run: |
        cat << EOF > "${{ runner.temp }}/.golangci.yaml"
        version: "2"
        linters:
          default: none
          enable:
          - staticcheck
          settings:
            staticcheck:
              checks:
              - ST*
              - -ST1000
              - -ST1020
              - -ST1021
              - -ST1022
        formatters:
          enable:
          - gofmt
          - goimports
        EOF

    - name: Lint
      uses: golangci/golangci-lint-action@v7
      with:
        args: '--config="${{ runner.temp }}/.golangci.yaml"'

  # Runs the build to ensure nothing is overtly broken.
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: gramLabs/.github/.github/actions/setup-go@main
      with:
        gh-token: '${{ secrets.gh-token }}'

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      if: hashFiles('.goreleaser.yml', '.goreleaser.yaml', 'goreleaser.yml', 'goreleaser.yaml') != ''
      with:
        args: build --single-target --snapshot

    - name: Run Go build
      if: hashFiles('.goreleaser.yml', '.goreleaser.yaml', 'goreleaser.yml', 'goreleaser.yaml') == ''
      run: go build ./...

  # Runs the short Go tests, callers may define additional jobs for more in-depth
  # acceptance testing on pull requests if necessary.
  test:
    name: Short Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: gramLabs/.github/.github/actions/setup-go@main
      with:
        gh-token: '${{ secrets.gh-token }}'

    - name: Test
      run: go test -short ./...
