name: Pull Request

on:
  workflow_call:
    inputs:
      go-version:
        description: 'Currently ignored in favor of the go.mod file.'
        default: '~1.17'
        required: false
        type: string
    secrets:
      gh-token:
        description: 'PAT used for pulling Go modules.'
        required: false

jobs:

  # Runs the linter with a minimal set of default rules.
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: gramLabs/.github/.github/actions/setup-go@main
      with:
        gh-token: '${{ secrets.gh-token }}'

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: -E goimports,stylecheck --timeout 2m
        skip-pkg-cache: true
        skip-build-cache: true

  # Runs the build to ensure nothing is overtly broken.
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: gramLabs/.github/.github/actions/setup-go@main
      with:
        gh-token: '${{ secrets.gh-token }}'

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3
      if: hashFiles('.goreleaser.yml', '.goreleaser.yaml', 'goreleaser.yml', 'goreleaser.yaml') != ''
      with:
        version: latest
        args: build --single-target --snapshot

    - name: Run Go build
      if: hashFiles('.goreleaser.yml', '.goreleaser.yaml', 'goreleaser.yml', 'goreleaser.yaml') == ''
      run: go build ./...

  # Runs the short Go tests, callers may define additional jobs for more in-depth
  # acceptance testing on pull requests if necessary.
  test:
    name: Short Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: gramLabs/.github/.github/actions/setup-go@main
      with:
        gh-token: '${{ secrets.gh-token }}'

    - name: Test
      run: go test -short ./...
