name: Pull Request

on:
  workflow_call:
    inputs:
      check-version-increment:
        description: "If true (default), `ct lint` will check for chart version increment"
        default: true
        required: false
        type: boolean
      check-install:
        description: "If true (default), install the chart on a Kind cluster and verify successful deployment"
        default: true
        required: false
        type: boolean


jobs:

  # Runs chart-testing over the Helm charts
  chart-test:
    name: Helm Chart Testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Set up Helm Chart Testing
      uses: helm/chart-testing-action@v2

    - name: List changed
      id: list-changed
      run: |
        if [[ -n "$(ct list-changed --target-branch $GITHUB_BASE_REF)" ]] ; then
          echo "changed=true" >> $GITHUB_OUTPUT
        fi

    - name: Lint
      run: ct lint --check-version-increment=${{ inputs.check-version-increment }} --target-branch $GITHUB_BASE_REF

    - name: Create kind cluster
      uses: helm/kind-action@v1
      if: ${{ inputs.check-install == 'true' && steps.list-changed.outputs.changed == 'true' }}

    - name: Install
      run: ct install --target-branch $GITHUB_BASE_REF
      if: ${{ inputs.check-install == 'true' && steps.list-changed.outputs.changed == 'true' }}
