name: Release

on:
  workflow_call:
    inputs:
      python-version:
        description: 'The Python version to download (if necessary) and use.'
        default: '3.10'
        required: false
        type: string
      image-name:
        description: 'The image name to generate.'
        required: true # TODO We should provide a default
        type: string
    secrets:
      registry-username:
        description: 'Username for the StormForge registry'
        required: true
      registry-password:
        description: 'Password for the StormForge registry'
        required: true

jobs:

  # Builds and pushes images to the private registry.
  deploy:
    name: Deploy Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: 'arm64'

    - name: Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to StormForge Registry
      uses: docker/login-action@v3
      with:
        registry: registry.stormforge.io
        username: '${{ secrets.registry-username }}'
        password: '${{ secrets.registry-password }}'

    - name: Docker Metadata
      uses: docker/metadata-action@v5
      id: meta
      with:
        images: registry.stormforge.io/${{ inputs.image-name }}
        flavor: latest=true
        tags: 'type=semver,pattern={{version}}'

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha
